# Generated by Django 5.1.6 on 2025-02-09 10:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        default=uuid.uuid4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
